bin/magento setup:install \
--base-url=http://magento2.loc \
--db-host=localhost \
--db-name=magento2 \
--db-user=sergey \
--db-password=Cthutq8! \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
